CarRentSystem/urls.py
from ajax_select import urls as ajax_select_urls
from django.conf import settings
from django.conf.urls import url
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

from car_management import urls as car_urls
from car_rent import urls as rent_urls
from trips import urls as trips_urls
from trip_stat import urls as trip_stat_urls

admin.autodiscover()

urlpatterns = [
                  # place it at whatever base url you like
                  url(r'^ajax_select/', include(ajax_select_urls)),
                  path('admin/', admin.site.urls),
                  url('', include(car_urls)),
                  url('', include(rent_urls)),
                  url('', include(trips_urls)),
                  url('', include(trip_stat_urls)),
              ] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

car_management/urls.py
from django.urls import path

from car_management.views import ViewCarExpenses, OperationsView, \
    TransactionView, ViewCarAccount, ViewInvestorAccount, ViewDriverAccount, ViewTaxiOperatorAccount, \
    ViewCounterpartAccount, ViewCarInvestmentAccount, test_view, dashboard, \
    ViewCashboxAccount
from trips.views.viewtrips import ViewCarWialons, ViewCarWialonsStat

urlpatterns = [
    path('cars', ViewCarAccount.as_view(), name='cars'),
    path('drivers', ViewDriverAccount.as_view(), name='drivers'),
    path('investors', ViewInvestorAccount.as_view(), name='investors'),
    path('taxi_operators', ViewTaxiOperatorAccount.as_view(), name='taxi_operators'),
    path('counterparts', ViewCounterpartAccount.as_view(), name='counterparts'),
    path('invest', ViewCarInvestmentAccount.as_view(), name='invest'),
    path('cashbox', ViewCashboxAccount.as_view(), name='cashbox'),



    path('car_wialon_trip/<car_name>/', ViewCarWialons.as_view(), name='wialon_trips_by_car'),
    path('car_wialon_trip', ViewCarWialons.as_view(), name='all_wialon_trips'),
    path('car_wialon_stat/<car_name>/', ViewCarWialonsStat.as_view(), name='wialon_stat_by_car'),
    path('car_wialon_stat', ViewCarWialonsStat.as_view(), name='all_wialon_stat'),
    path('car_expenses', ViewCarExpenses.as_view(), name='all_expenses'),
    path('car_expenses/<car_name>/', ViewCarExpenses.as_view(), name='expenses_by_car'),
    path('operations', OperationsView.as_view(), name='all_operations'),
    path('transactions', TransactionView.as_view(), name='all_transactions'),
    path('dashboard', dashboard, name='dashboard'),

    path('test_view', test_view),


]

trips/urls.py
from django.urls import path

from trips.views.viewtrips import ViewCarWialons, ViewCarWialonsStat, ViewTrips, ViewTripsNew, ViewTripsNew2, \
    ViewCarTrips
from trips.views.carview import ViewCarStatistic, car_usage_report

urlpatterns = [
    path('car_trip', ViewCarTrips.as_view(), name='all_trips'),
    path('car_wialon_trip/<car_name>/', ViewCarWialons.as_view(), name='wialon_trips_by_car'),
    path('car_wialon_trip', ViewCarWialons.as_view(), name='all_wialon_trips'),
    path('car_wialon_stat/<car_name>/', ViewCarWialonsStat.as_view(), name='wialon_stat_by_car'),
    path('car_wialon_stat', ViewCarWialonsStat.as_view(), name='all_wialon_stat'),
    path('car_trip/<car_name>/', ViewCarTrips.as_view(), name='trip_by_car'),
    path('car_stat', ViewCarStatistic.as_view(), name='trip_stat'),
    path('car_stat/<car_name>/', ViewCarStatistic.as_view(), name='trip_stat_by_car'),
    path('car_report', car_usage_report, name='car_report'),

    path('test/', ViewTrips.as_view()),
    path('json/', ViewTripsNew.as_view()),
    path('json2/', ViewTripsNew2.as_view()),

]

balance/models.py
from datetime import datetime, date

from django.db import models
# Create your models here.
from django.db.models import Sum
from django.utils.timezone import now


class Account(models.Model):
    class AccountCurrency(models.IntegerChoices):
        GRIVNA = 0, 'грн'
        DOLLAR = 1, '$'

    name = models.CharField(max_length=250, verbose_name='имя/название/гос номер')
    last_period_balance = models.ForeignKey('AccountStatement', null=True, on_delete=models.SET_NULL,
                                            related_name='for_account', blank=True,
                                            verbose_name='Последний зафиксированный баланс'
                                            )
    currency = models.PositiveSmallIntegerField(choices=AccountCurrency.choices, default=AccountCurrency.GRIVNA,
                                                verbose_name='валюта')

    def __str__(self):
        account_str = f'{self.last_period_balance.closingBalance} ' \
                      f'{self.last_period_balance.statementDate.strftime("%d.%m.%Y")}' \
            if self.last_period_balance else '--'
        return f'{self.name} ({account_str}){self.get_currency()}'

    class Meta:
        verbose_name = 'Баланс'
        verbose_name_plural = 'Балансы'
        ordering = ('name',)

    def get_currency(self):
        return Account.AccountCurrency.labels[self.currency]

    # return last statement balance for account on date
    def get_statement_balance(self, on_date: date):
        if on_date is None:
            on_date = now().date()
        else:
            if isinstance(on_date, datetime):
                on_date = on_date.date()
        if self.last_period_balance is not None and self.last_period_balance.statementDate <= on_date:
            last_balance = self.last_period_balance
        else:
            last_balance = AccountStatement.objects.filter(account_id=self.pk, statementDate__lte=on_date).order_by(
                '-statementDate').first()

        if last_balance is None:
            return 0, None, None
        return last_balance.closingBalance, last_balance.statementDate, last_balance

    def get_current_balance(self, on_date=None) -> int:

        if on_date is None:
            on_date = now()
        balance, from_date, _ = self.get_statement_balance(on_date)
        if from_date is not None:
            total = AccountTransaction.objects.filter(account=self,
                                                      transaction__transactionTime__gt=from_date,
                                                      transaction__transactionTime__lte=on_date).aggregate(
                Sum('amount'))['amount__sum']
            balance = balance + (total if total is not None else 0)
        else:
            balance = AccountTransaction.objects.filter(account=self,
                                                        transaction__transactionTime__lte=on_date).aggregate(
                Sum('amount'))['amount__sum']
            balance = balance if balance is not None else 0
        return balance

    def form_statement(self, on_date=None):
        if on_date is None:
            on_date = now()
        old_balance, from_date, statement_balance = self.get_statement_balance(on_date)
        if statement_balance:
            return statement_balance
        if from_date is not None:
            credit = AccountTransaction.objects.filter(account=self, amount__lt=0,
                                                       transaction__transactionTime__gt=from_date,
                                                       transaction__transactionTime__lte=on_date).aggregate(
                Sum('amount'))['amount__sum']
            debit = AccountTransaction.objects.filter(account=self, amount__gt=0,
                                                      transaction__transactionTime__gt=from_date,
                                                      transaction__transactionTime__lte=on_date).aggregate(
                Sum('amount'))['amount__sum']
        else:
            old_balance = 0
            credit = AccountTransaction.objects.filter(account=self, amount__lt=0,
                                                       transaction__transactionTime__lte=on_date).aggregate(
                Sum('amount'))['amount__sum']
            debit = AccountTransaction.objects.filter(account=self, amount__gt=0,
                                                      transaction__transactionTime__lte=on_date).aggregate(
                Sum('amount'))['amount__sum']
        debit = int(0 if debit is None else debit)
        credit = int(0 if credit is None else credit)
        balance = old_balance + debit + credit

        statement_balance = AccountStatement(account=self, statementDate=on_date, closingBalance=balance,
                                             totalDebit=debit, totalCredit=credit)
        statement_balance.save()
        no_update = AccountStatement.objects.filter(account=self, statementDate__gt=on_date).exists()
        if not no_update:
            self.last_period_balance = statement_balance
            self.save()
        return statement_balance

    def current_balance(self):
        balance = self.get_current_balance()
        return balance / 100 if balance else 0

    def last_statemnet_balance(self):
        if self.last_period_balance:
            return self.last_period_balance.closingBalance / 100
        else:
            return 0

    def last_statemnet_debit(self):
        if self.last_period_balance:
            return self.last_period_balance.totalDebit / 100
        else:
            return 0

    def last_statemnet_credit(self):
        if self.last_period_balance:
            return self.last_period_balance.totalCredit / 100
        else:
            return 0

    def last_statemnet_date(self):
        if self.last_period_balance:
            return self.last_period_balance.statementDate.strftime('%d.%m.%Y')
        else:
            return '---'


class AccountStatement(models.Model):
    statementDate = models.DateField()
    account = models.ForeignKey(Account, on_delete=models.CASCADE)
    closingBalance = models.BigIntegerField()
    totalCredit = models.BigIntegerField()
    totalDebit = models.BigIntegerField()

    def __str__(self):
        return f'S[{self.statementDate.strftime("%Y.%m.%d")}:' \
               f'{self.account.name}] = {self.closingBalance},{self.totalDebit},{self.totalCredit} ' \
               f'{Account.AccountCurrency.labels[self.account.currency]}'

    class Meta:
        verbose_name = 'Состояния баланса за дату'
        verbose_name_plural = 'Переодические состояния балансов'
        ordering = ('account', 'statementDate')
        unique_together = ('account', 'statementDate')


class Transaction(models.Model):
    class TransactionType(models.IntegerChoices):
        EXPENSE = 0, 'Расход'
        RECEIPT = 1, 'Приход'
        TRANSFER = 3, 'Перевод средств между счетами'
        DEPOSIT = 4, 'Внесение денежных средств '
        WITHDRAWAL = 5, 'Вывод денежных средств'
        INVESTMENT = 6, 'Инвестиция'
        INSURANCE = 7, 'Строховка'

    transactionTime = models.DateTimeField(auto_now_add=True, verbose_name='Время транзакции')
    transactionType = models.IntegerField(choices=TransactionType.choices, verbose_name='Тип')
    comment = models.TextField(max_length=1000, default='', blank=True, null=True)

    class Meta:
        verbose_name = 'Транзакция'
        verbose_name_plural = 'транзакции'

    def get_transaction_type(self):
        for el in Transaction.TransactionType.choices:
            if el[0] == self.transactionType:
                return el[1]
        return '--'

    def __str__(self):
        return f'{self.pk} [{self.transactionTime.strftime("%d.%m.%Y %H:%M:%S")}] - {self.get_transaction_type()}'


class AccountTransaction(models.Model):
    transaction = models.ForeignKey(Transaction, on_delete=models.CASCADE)
    account = models.ForeignKey(Account, on_delete=models.CASCADE)
    amount = models.BigIntegerField()
    comment = models.CharField(max_length=100, default='', blank=True, null=True)

    def __str__(self):
        return f'T[{self.transaction.id}] {self.account.name} {self.amount}{Account.AccountCurrency.labels[self.account.currency]}'

    class Meta:
        verbose_name = 'Операция в транзакция'
        verbose_name_plural = 'Транзакционные операции'


    def cents_amount(self):
        return f'{self.amount / 100:.2f}'


class CashBox(Account):
    class Meta:
        verbose_name = 'Касса'
        verbose_name_plural = 'Кассы'

    def __str__(self):
        cash = self.get_current_balance()
        cash = cash/100 if cash else 0
        return f'{self.name} {cash:.2f}{self.get_currency()}'

car_management/models/intervals.py
from django.db import models


class TimeType(models.IntegerChoices):
    HOUR = (1, 'Учет в часах')
    DAYS = (2, 'Учет в днях')
    WEEK = (3, 'Учет в неделях')
    MONTH = (4, 'Учет в месяцах')

car_management/views/accounting.py
from django.contrib.auth.mixins import LoginRequiredMixin

from balance.models import CashBox
from car_management.models import Car, Investor, Driver, Counterpart
from car_management.views.global_menu import GlobalMainMenu
from car_rent.models import TaxiOperator
from django_helpers.django_request_processor import UniversalFilterListView


class ViewCarAccount(LoginRequiredMixin, UniversalFilterListView, GlobalMainMenu):
    model = Car
    login_url = '/admin/login/'
    template_name = 'carmanagment/acccount_list.html'
    paginate_by = 20
    filtering = (
        ('name',),
    )


class ViewCarInvestmentAccount(ViewCarAccount, GlobalMainMenu):
    model = Car
    template_name = 'carmanagment/inest_list.html'
    paginate_by = 20
    filtering = (
        ('name',),
    )


class ViewInvestorAccount(ViewCarAccount, GlobalMainMenu):
    model = Investor


class ViewCashboxAccount(ViewCarAccount, GlobalMainMenu):
    model = CashBox


class ViewDriverAccount(ViewCarAccount, GlobalMainMenu):
    model = Driver


class ViewCounterpartAccount(ViewCarAccount, GlobalMainMenu):
    model = Counterpart


class ViewTaxiOperatorAccount(ViewCarAccount, GlobalMainMenu):
    model = TaxiOperator

car_management/views/dashboard.py
import json

from django.contrib.auth.decorators import login_required
from django.shortcuts import render

from car_management.views.global_menu import GlobalMainMenu
from trip_stat.services.statisrics_service import Statistics


@login_required
def dashboard(request):
    import random

    def getRandomCol():

        r = hex(random.randrange(0, 16))[2:] + hex(random.randrange(0, 16))[2:]
        g = hex(random.randrange(0, 255))[2:] + hex(random.randrange(0, 16))[2:]
        b = hex(random.randrange(0, 255))[2:] + hex(random.randrange(0, 16))[2:]

        random_col = '#' + r[:2] + g[:2] + b[:2]
        return random_col

    context = GlobalMainMenu.form_menu_context(request)
    trip_stat = Statistics.get_last_statistics()
    context['page_header'] = 'DashBoard'
    trip_data = []
    trip_sum = []
    trip_label = []
    trip_color = []
    for index, (name, stats) in enumerate(trip_stat.items()):
        trip_data.append(
            {'name': name,
             'data': [el.trip_count for el in stats]})
        trip_sum.append(
            {'name': name,
             'data': [el.amount for el in stats]})
        trip_color.append(getRandomCol())
        if index == 0:
            trip_label = [el.stat_date.strftime('%d.%m.%y') for el in stats]

    context['trips_data'] = trip_data
    context['trips_sum'] = trip_sum
    context['cars'] = json.dumps(trip_label)
    context['colors'] = json.dumps(trip_color)
    return render(request, 'admin_template/dashboard.html', context)

car_management/views/expenses.py
from django.contrib.auth.mixins import LoginRequiredMixin

from car_management.models import Expenses, Car
from trips.views.carview import ByCarView
from car_management.views.global_menu import GlobalMainMenu
from django_helpers.django_request_processor import UniversalFilterListView


class ViewCarExpenses(UniversalFilterListView, ByCarView, GlobalMainMenu):
    model = Expenses
    template_name = 'carmanagment/cars_expenses_list.html'
    paginate_by = 20
    ordering = ('-date_mark',)
    filtering = (
        ('account__name__icontains', 'name'),
        ('date_mark__gte', 'start_interval'),
        ('date_mark__lte', 'end_interval'),
    )

    def get_queryset(self):
        if self.current_car:
            self.queryset = Expenses.objects.filter(account=self.current_car)
        else:
            self.queryset = Expenses.objects.filter(account__pk__in=Car.objects.values('pk').all())
        return super().get_queryset()

car_management/views/operations.py
from django.contrib.auth.mixins import LoginRequiredMixin

from balance.models import AccountTransaction, Transaction
from car_management.views.global_menu import GlobalMainMenu
from django_helpers.django_request_processor import UniversalFilterListView


class OperationsView(LoginRequiredMixin, UniversalFilterListView, GlobalMainMenu):
    model = AccountTransaction
    login_url = '/admin/login/'
    template_name = 'carmanagment/operation_list.html'
    paginate_by = 20
    filtering = (
        ('account__name__icontains', 'name'),
        ('transaction__transactionTime__gte', 'start_interval'),
        ('transaction__transactionTime__lte', 'end_interval'),
    )


class TransactionView(LoginRequiredMixin, UniversalFilterListView, GlobalMainMenu):
    model = Transaction
    login_url = '/admin/login/'
    template_name = 'carmanagment/transaction_list.html'
    paginate_by = 20
    filtering = (
        ('transactionTime__gte', 'start_interval'),
        ('transactionTime__lte', 'end_interval'),
    )

car_management/views/other.py
from django.shortcuts import render


def test_view(request):
    return render(request, 'admin_template/base_template.html', {})

car_management/templates/carmanagment/acccount_list.html
{% extends 'admin_template/base_template.html' %}
{% load fw_paginator %}
{% block PAGE_CONTENT %}
    <div class="card">
    <div class="card-header">
        <h4 class="card-title">Список поездок</h4>
    </div>
    <div class="card-content">
        <div class="card-body">
            <form method="get" class="form form-horizontal">
                <div class="form-body">
                    <div class="row">
                        <div class="col-md-8">
                            <input type="text" name="name" placeholder="car plate" class="form-control round"
                                   value="{{ filter_form_values.name }}"/>
                        </div>
                        <div class="col-md-4 d-flex justify-content-end">
                            <button type="submit" class="btn btn-primary me-1 mb-1">Submit</button>
                            <button type="reset" class="btn btn-light-secondary me-1 mb-1">Reset
                            </button>
                        </div>
                    </div>
                </div>
            </form>
        </div>
        <!-- table head dark -->
        <div class="table-responsive">
            <table class="table mb-0">
                <thead class="thead-dark">
                <tr>
                            <th>Акаунт</th>
                            <th>Текущий баланс</th>
                            <th>Валюта</th>
                            <th>На период</th>
                            <th>Баланс</th>
                            <th>Дебит</th>
                            <th>Кредит</th>
                </tr>
                </thead>
                <tbody>
                {% for obj in object_list %}
                    <tr>
                                <td>{{ obj.name }}</td>
                                <td>{{ obj.current_balance|floatformat:2}}</td>
                                <td>{{ obj.get_currency }}</td>
                                <td>{{ obj.last_statemnet_date}}</td>
                                <td>{{ obj.last_statemnet_balance|floatformat:2}}</td>
                                <td>{{ obj.last_statemnet_debit|floatformat:2}}</td>
                                <td>{{ obj.last_statemnet_credit|floatformat:2}}</td>
                    </tr>
                {% endfor %}
                </tbody>
            </table>
        </div>
        <div class="row">
            <div class="col-12 d-flex justify-content-center">
                {% paging_navigation page_obj %}
            </div>
        </div>
    </div>
    </div>
{% endblock %}

car_management/templates/carmanagment/cars_expenses_list.html
{% extends 'admin_template/base_template_submenu.html' %}
{% load fw_paginator %}
{% block MAIN_SUB_MENU_BLK %}
    <div id="list" class="card">
        <div class="card-header">
            ФИЛТЕР
        </div>
        <div class="card-content">
            <div class="nav flex-column nav-pills" id="v-pills-tab" role="tablist" aria-orientation="vertical">
                {% for car in cars %}
                    {% if car == current_car %}
                        <a href="{% url 'expenses_by_car' car.name %}" class="nav-link active">
                    {% else %}
                        <a href="{% url 'expenses_by_car' car.name %}" class="nav-link">
                    {% endif %}


                {{ car.model }}
                <span>{{ car.name }}</span>
                </a>

                {% endfor %}
            </div>
        </div>
    </div>

{% endblock %}
{% block MAIN_CONTENT_BLK %}
    <div class="card-header">
        <h4 class="card-title">Список поездок</h4>
    </div>
    <div class="card-content">
        <div class="card-body">
            <p class="email-content-subtitle">
                {% if current_car.name %}
                    Авто <a>{{ current_car.name }}</a>
                {% endif %}
                {% if filter_form_values.start_interval %}
                    c <span>{{ filter_form_values.start_interval }}</span>
                {% endif %}
                {% if filter_form_values.end_interval %}
                    по <span>{{ filter_form_values.end_interval }}</span>
                {% endif %}
            </p>
            <form method="get" class="form form-horizontal">
                <div class="form-body">
                    <div class="row">
                        <div class="col-md-3">
                            <input type="date" name="start_interval" placeholder="from"
                                   class="form-control round"
                                   value="{{ filter_form_values.start_interval }}"/>
                        </div>
                        <div class="col-md-3">
                            <input type="date" name="end_interval" placeholder="to" class="form-control round"
                                   value="{{ filter_form_values.end_interval }}"/>
                        </div>
                        <div class="col-md-3">
                            <input type="text" name="name" placeholder="car plate" class="form-control round"
                                   value="{{ filter_form_values.name }}"/>
                        </div>
                        <div class="col-md-3 d-flex justify-content-end">
                            <button type="submit" class="btn btn-primary me-1 mb-1">Submit</button>
                            <button type="reset" class="btn btn-light-secondary me-1 mb-1">Reset
                            </button>
                        </div>
                    </div>
                </div>
            </form>
        </div>
        <!-- table head dark -->
        <div class="table-responsive">
            <table class="table mb-0">
                <thead class="thead-dark">
                <tr>
                            <th>Дата</th>
                            <th>Машина</th>
                            <th>Тип затраты</th>
                            <th>Сумма</th>
                            <th>Описание</th>
                </tr>
                </thead>
                <tbody>
                {% for obj in object_list %}
                    <tr>
                                <td>{{ obj.date_mark|date:'d-m-Y H:i:s' }}</td>
                                <td>{{ obj.account.name }}</td>
                                <td>{{ obj.expenseType.name }}</td>
                                <td>{{ obj.amount|floatformat:2 }} грн</td>
                                <td>{{ obj.description }}</td>
                    </tr>
                {% endfor %}
                </tbody>
            </table>
        </div>
        <div class="row align-self-end">
            <div class="col-12 d-flex justify-content-center">
                {% paging_navigation page_obj %}
            </div>
        </div>
    </div>
{% endblock %}

car_management/templates/carmanagment/inest_list.html
{% extends 'admin_template/base_template.html' %}
{% load fw_paginator %}
{% block PAGE_CONTENT %}
    <div class="card">
    <div class="card-header">
        <h4 class="card-title">Список поездок</h4>
    </div>
    <div class="card-content">
        <div class="card-body">
            <form method="get" class="form form-horizontal">
                <div class="form-body">
                    <div class="row">
                        <div class="col-md-8">
                            <input type="text" name="name" placeholder="car plate" class="form-control round"
                                   value="{{ filter_form_values.name }}"/>
                        </div>
                        <div class="col-md-4 d-flex justify-content-end">
                            <button type="submit" class="btn btn-primary me-1 mb-1">Submit</button>
                            <button type="reset" class="btn btn-light-secondary me-1 mb-1">Reset
                            </button>
                        </div>
                    </div>
                </div>
            </form>
        </div>
        <!-- table head dark -->
        <div class="table-responsive">
            <table class="table mb-0">
                <thead class="thead-dark">
                <tr>
                            <th>Акаунт</th>
                            <th>Текущий баланс</th>
                            <th>Валюта</th>
                            <th>На период</th>
                            <th>Баланс</th>
                            <th>Дебит</th>
                            <th>Кредит</th>
                </tr>
                </thead>
                <tbody>
                {% for obj in object_list %}
                    <tr>
                                <td>{{ obj.investment.name }}</td>
                                <td>{{ obj.investment.current_balance|floatformat:2}}</td>
                                <td>{{ obj.investment.get_currency }}</td>
                                <td>{{ obj.investment.last_statemnet_date}}</td>
                                <td>{{ obj.investment.last_statemnet_balance|floatformat:2}}</td>
                                <td>{{ obj.investment.last_statemnet_debit|floatformat:2}}</td>
                                <td>{{ obj.investment.last_statemnet_credit|floatformat:2}}</td>
                    </tr>
                {% endfor %}
                </tbody>
            </table>
        </div>
        <div class="row">
            <div class="col-12 d-flex justify-content-center">
                {% paging_navigation page_obj %}
            </div>
        </div>
    </div>
    </div>
{% endblock %}

car_management/templates/carmanagment/transaction_list.html
{% extends 'admin_template/base_template.html' %}
{% load fw_paginator %}
{% block PAGE_CONTENT %}
    <div class="card">
    <div class="card-header">
        <h4 class="card-title">Список операций</h4>
                    <p class="email-content-subtitle">
                        {% if filter_form_values.name %}
                        Баланс <a>{{ filter_form_values.name }}</a>
                        {% endif %}
                        {% if filter_form_values.start_interval %}
                        c <span>{{ filter_form_values.start_interval }}</span>
                        {% endif %}
                        {% if filter_form_values.end_interval %}
                        по <span>{{ filter_form_values.end_interval }}</span>
                        {% endif %}
                    </p>
    </div>
    <div class="card-content">
        <div class="card-body">
            <form method="get" class="form form-horizontal">
                <div class="form-body">
                    <div class="row">
                        <div class="col-md-3">
                            <input type="date" name="start_interval" placeholder="from"
                                   class="form-control round"
                                   value="{{ filter_form_values.start_interval }}"/>
                        </div>
                        <div class="col-md-3">
                            <input type="date" name="end_interval" placeholder="to" class="form-control round"
                                   value="{{ filter_form_values.end_interval }}"/>
                        </div>
                        <div class="col-md-3">
                            <input type="text" name="name" placeholder="баланс" class="form-control round"
                                   value="{{ filter_form_values.name }}"/>
                        </div>
                        <div class="col-md-3 d-flex justify-content-end">
                            <button type="submit" class="btn btn-primary me-1 mb-1">Submit</button>
                            <button type="reset" class="btn btn-light-secondary me-1 mb-1">Reset
                            </button>
                        </div>
                    </div>
                </div>
            </form>
        </div>
        <!-- table head dark -->
        <div class="table-responsive">
            <table class="table mb-0">
                <thead class="thead-dark">
                    <tr>
                            <th>Транзакция</th>
                            <th>Дата</th>
                            <th colspan="3">Коментарий</th>
                        </tr>
                        <tr>
                            <th></th>
                            <th></th>
                            <th>Акаунт</th>
                            <th>Сумма</th>
                            <th>Примечание</th>
                        </tr>
                </thead>
                <tbody>
                        {% for obj in object_list %}
                            <tr>
                                <td>{{ obj.id }}</td>
                                <td>{{ obj.transactionTime|date:'d-m-Y H:i:s' }}</td>
                                <td colspan="3">{{ obj.comment }}</td>
                            </tr>
                            <tr>
                                    {% for oper in obj.accounttransaction_set.all %}
                                        <tr>
                                            <td></td>
                                            <td></td>
                                            <td>{{ oper.account.name }}</td>
                                            <td>{{ oper.cents_amount|floatformat:2 }} {{ obj.account.get_currency }}</td>
                                            <td>{{ oper.comment }}</td>
                                        </tr>
                                    {% endfor %}
                            </tr>
                        {% endfor %}
                </tbody>
            </table>
        </div>
        <div class="row">
            <div class="col-12 d-flex justify-content-center">
                {% paging_navigation page_obj %}
            </div>
        </div>
    </div>
    </div>
{% endblock %}